quarkus:
  application:
    name: smart-hub
    version: ${SMART_HUB_VERSION}
  datasource:
    db-kind: postgresql
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    reactive:
      url: postgresql://${DB_HOST}:5432/${DB_NAME}
smart-hub:
  mqtt-client:
    host: ${BROKER_HOST}
    port: ${BROKER_PORT}
    client-id: smart-hub-client
    user-name: ${BROKER_USER}
    password: ${BROKER_PASSWORD}
    topics:
      device-provisioning: devices/provisioning
