quarkus:
  mongodb:
    connection-string: mongodb://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:27017/${DB_NAME}?authSource=admin
    database: ${DB_NAME}
  application:
    name: smart-hub
    version: ${SMART_HUB_VERSION}

smart-hub:
  iot:
    client-id: smart-hub
    host: ${BROKER_HOST}
    port: ${BROKER_PORT}
    username: ${BROKER_USERNAME}
    password: ${BROKER_PASSWORD}
    topics:
      device-provisioning: devices/provisioning