
quarkus:
  application:
    name: smart-hub
    version: ${SMART_HUB_VERSION}
  log:
    console:
      color: true
    level: INFO
  mongodb:
    application-name: smart-hub
    credentials:
      password: ${DB_PASSWORD}
      username: ${DB_USER}
    connection-string: mongodb://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:27017/${DB_NAME}
    database: ${DB_NAME}
mp:
  openapi:
    extensions:
      smallrye:
        operationIdStrategy: METHOD
        openapi: 3.0.2
        info:
          title: Smart Hub API
          version: ${SMART_HUB_VERSION}
          description: Smart Hub API to check or interact with your smart home devices