spring:
  application:
    name: smart-hub
  rabbitmq:
    host: ${RABBITMQ_HOST}
    password: ${RABBITMQ_PASSWORD}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USER}
  data:
    mongodb:
      database: ${DB_NAME}
      host: ${DB_HOST}

smart-hub:
  device-provisioning-queue-name: device-provisioning
  device-provisioning-topic-name: device.provisioning
