micronaut:
  application:
    name: smartHub
mqtt:
  client:
    server-uri: tcp://${BROKER_HOST}:${BROKER_PORT}
    client-id: SmartHubClient
    user-name: ${BROKER_USER}
    password: ${BROKER_PASSWORD}
    clean-start: true
    clean-session: true
vertx:
  pg:
    client:
      port: 5432
      host: ${DB_HOST}
      database: ${DB_NAME}
      user: ${DB_USER}
      password: ${DB_PASSWORD}
      maxSize: 5
