spring:
  r2dbc:
    password: ${DB_PASSWORD}
    name: ${DB_NAME}
    username: ${DB_USERNAME}
    url: r2dbc:pool:postgresql://${DB_HOST}:5432/${DB_NAME}?schema=public
    pool:
      validation-query: select 1

logging:
  level:
    web: DEBUG
    org:
      springframework:
        data:
          r2dbc: DEBUG