smart-hub:
  iot:
    broker:
      client-id: ${BROKER_CLIENT_ID}
      host: ${BROKER_HOST}
      port: ${BROKER_PORT}
      username: ${BROKER_USER}
      password: ${BROKER_PASSWORD}
    topics:
      device-provisioning: devices/provisioning

quarkus:
  application:
    name: smart-hub
    version: ${SMART_HUB_VERSION}
  datasource:
    db-kind: postgresql
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    reactive:
      url: postgresql://${DB_HOST}:5432/${DB_NAME}
  log:
    console:
      color: true
    level: INFO

mp:
  openapi:
    extensions:
      smallrye:
        operationIdStrategy: METHOD
        openapi: 3.0.2
        info:
          title: Smart Hub API
          version: ${SMART_HUB_VERSION}
          description: Smart Hub API to check or interact with your smart home devices

"%dev":
  mp:
    openapi:
      extensions:
        smallrye:
          info:
            title: Smart Hub API (development)