# => Server settings
quarkus:
  http:
    port: 8081
  # => Datasource settings
  datasource:
    reactive:
      url: postgresql://${POSTGRES_HOST}:5432/${DB_NAME}
    db-kind: postgresql
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}


smart-hub:
  mqtt-broker:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASSWORD}
    mqtt-exchange: amq.topic
  queues:
    device-provisioning-queue: device-provisioning
    device-provisioning-topic: device.provisioning
