smart-hub:
  iot:
    broker:
      client-id: ${BROKER_CLIENT_ID}
      host: ${BROKER_HOST}
      port: ${BROKER_PORT}
      username: ${BROKER_USERNAME}
      password: ${BROKER_PASSWORD}
    topics:
      device-provisioning: devices/provisioning

quarkus:
  application:
    name: smart-hub
    version: ${SMART_HUB_VERSION}
  datasource:
    db-kind: postgresql
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    reactive:
      url: postgresql://${DB_HOST}:5432/${DB_NAME}
  log:
    console:
      color: true