quarkus:
  application:
    name: smart-hub
    version: ${SMART_HUB_VERSION}
  container-image:
    group: iot-tetracube-red
    name: smart-hub
    tag: ${SMART_HUB_VERSION}
smart-hub:
  mqtt:
    host: ${RABBITMQ_HOST}
    port: 1883
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASSWORD}
    topics:
      device-provisioning: device/provisioning
      device-feedback: device/feedback
