quarkus:
  application:
    name: smart-hub
    version: ${SMART_HUB_VERSION}
  datasource:
    db-kind: postgresql
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    reactive:
      url: postgresql://${DB_HOST}:5432/${DB_NAME}
  http:
    cors: true
    port: 8080
    host: 0.0.0.0
  smallrye-openapi:
    enable: true
    path: /docs
  swagger-ui:
    enable: true
    always-include: true
    path: /docs-ui
smart-hub:
  mqtt-client:
    host: ${BROKER_HOST}
    port: ${BROKER_PORT}
    client-id: smart-hub-client
    user-name: ${BROKER_USER}
    password: ${BROKER_PASSWORD}
    topics:
      device-provisioning: devices/provisioning