version: '3.8'

networks:
  smart-hub-network:

services:
  smart-hub-broker:
    build:
      context: ./iot-broker
      dockerfile: Dockerfile
    container_name: smart-hub-broker
    restart: on-failure
    ports:
      - 1883:1883
      - 15672:15672
      - 5672:5672
    networks:
      - smart-hub-network
    env_file:
      - .env
  smart-hub-db:
    image: postgres:alpine
    container_name: smart-hub-db
    restart: on-failure
    ports:
      - 5432:5432
    networks:
      - smart-hub-network
    env_file:
      - .env
