version: '3.8'

networks:
  smart-hub-network:

services:
  smart-hub-broker:
    image: hivemq/hivemq-ce
    container_name: smart-hub-broker
    restart: on-failure
    ports:
      - 1883:1883
      - 8000:8000
    networks:
      - smart-hub-network
    env_file:
      - broker.env

  smart-hub-db:
    image: postgres:latest
    container_name: smart-hub-db
    restart: on-failure
    ports:
      - 5432:5432
    networks:
      - smart-hub-network
    env_file: 
      - db.env
