version: '3.8'

networks:
  smart-hub-network:

services:
  smart-hub-broker:
    image: emqx/emqx
    container_name: smart-hub-broker
    restart: on-failure
    ports:
      - 1883:1883
      - 18083:18083
    networks:
      - smart-hub-network
    env_file:
      - broker.env
    environment:
      - EMQX_ALLOW_ANONYMOUS=false
      - EMQX_LOADED_PLUGINS=emqx_recon,emqx_retainer,emqx_management,emqx_dashboard,emqx_auth_mongo
      - EMQX_AUTH__MONGO__SERVER=smart-hub-db:27017
      - EMQX_AUTH__MONGO__TYPE=single
      - EMQX_AUTH__MONGO__TOPOLOGY__POOL_SIZE=1
      - EMQX_AUTH__MONGO__TOPOLOGY__MAX_OVERFLOW=0
      - EMQX_AUTH__MONGO__POOL=8
      - EMQX_AUTH__MONGO__AUTH_SOURCE=admin
      - EMQX_AUTH__MONGO__QUERY_TIMEOUT=5s
      - EMQX_AUTH__MONGO__PASSWORD_HASH=sha256
      - EMQX_AUTH__MONGO__AUTH_QUERY__COLLECTION=mqtt_user
      - EMQX_AUTH__MONGO__AUTH_QUERY__PASSWORD_FIELD=password
      - EMQX_AUTH__MONGO__AUTH_QUERY__SELECTOR=username=%u, client_id=%c
      - EMQX_LOG__LEVEL=debug

  smart-hub-db:
    image: mongo:latest
    container_name: smart-hub-db
    restart: on-failure
    ports:
      - 27017:27017
    networks:
      - smart-hub-network
    env_file: 
      - db.env
