version: '3.8'

networks:
  smart-hub-network:

services:
  smart-hub-broker:
    image: vernemq/vernemq
    container_name: smart-hub-broker
    restart: on-failure
    ports:
      - 1883:1883
      - 8888:8888
    networks:
      - smart-hub-network
    environment:
      - DOCKER_VERNEMQ_LISTENER__TCP__ALLOWED_PROTOCOL_versions=3,4,5
      - DOCKER_VERNEMQ_ACCEPT_EULA=yes
    env_file:
      - broker.env

  smart-hub-db:
    image: postgres:latest
    container_name: smart-hub-db
    restart: on-failure
    ports:
      - 5432:5432
    networks:
      - smart-hub-network
    env_file: 
      - db.env
